name = "littensy/charm"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
React = { wally = "jsdotlua/react", version = "^17.2.1" }
ReactRoblox = { wally = "jsdotlua/react-roblox", version = "^17.2.1" }
Vide = { wally = "centau/vide", version = "^0.3.1" }
