[package]
name = "littensy/react-charm"
version = "0.4.0-rc.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"node_modules",
	"test",
	"src/index.d.ts",
	"package.json",
	"React.luau",
	"Charm.luau",
]

[dependencies]
Charm = "littensy/charm@^0.11.0-rc.6"
React = "jsdotlua/react@^17"
