[package]
name = "littensy/vide-charm"
version = "0.4.0-rc.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"node_modules",
	"test",
	"src/index.d.ts",
	"package.json",
	"Vide.luau",
	"Charm.luau",
]

[dependencies]
Charm = "littensy/charm@^0.11.0-rc.5"
Vide = "centau/vide@^0.4"
